services:
  ollama:
    container_name: choco-coco-brain
    restart: unless-stopped
    image: ollama/ollama:0.22.1
    volumes:
      - ./run_ollama.sh:/run_ollama.sh:Z
      - ./ollama:/root/.ollama:Z
    env_file:
      - .env
    environment:
      - OLLAMA_LLM_MODEL=${OLLAMA_LLM_MODEL}
      - EMBEDDER_MODEL=${EMBEDDER_MODEL}
    ports:
      - "${OLLAMA_PORT}:${OLLAMA_PORT}"

    entrypoint:
      - /bin/bash
      - -c
      - |
        ollama serve &

        until ollama list > /dev/null 2>&1; do
          sleep 1
        done

        ollama pull "$OLLAMA_LLM_MODEL"
        ollama pull "$EMBEDDER_MODEL"

        wait

    networks:
      - ollama_network

  choco-coco-api:
    container_name: choco-coco-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      args:
        - API_PORT=${API_PORT}
    depends_on:
      - ollama
    env_file:
      - .env
    networks:
      - ollama_network
    ports:
      - "${API_PORT}:${API_PORT}"

  zrok2:
    image: openziti/zrok:v2__0_zrok2
    user: "root"
    volumes:
      - ${HOME_DIRECTORY}/.zrok2:/home/ziggy/.zrok2:Z
    env_file:
      - .env
    networks:
      - ollama_network
    environment:
      - PFXLOG_NO_JSON=true
      - API_PORT=${API_PORT}
      - HOME_DIRECTORY=${HOME_DIRECTORY}
    command: share public http://choco-coco-api:${API_PORT} --headless

networks:
  ollama_network:
    driver: bridge
