[package]
name = "choco-coco-image-to-ascii"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "choco_coco_image_to_ascii"
crate-type = ["cdylib", "rlib"]

[dependencies]
libasciic = "1.1.1"
pyo3 = "0.27.0"
pyo3-stub-gen = "0.22.2"
