# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins

__all__ = [
    "image_to_ascii",
]

def image_to_ascii(
    path_image: builtins.str, width: builtins.int, height: builtins.int
) -> builtins.str: ...
